#!/bin/sh
set -eu

mariadb -uroot -p"${MARIADB_ROOT_PASSWORD}" <<-EOSQL
  CREATE DATABASE IF NOT EXISTS \`${GITEA_DB_NAME}\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
  CREATE DATABASE IF NOT EXISTS \`${NEXTCLOUD_DB_NAME}\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

  CREATE USER IF NOT EXISTS '${GITEA_DB_USER}'@'%' IDENTIFIED BY '${GITEA_DB_PASSWORD}';
  CREATE USER IF NOT EXISTS '${NEXTCLOUD_DB_USER}'@'%' IDENTIFIED BY '${NEXTCLOUD_DB_PASSWORD}';

  GRANT ALL PRIVILEGES ON \`${GITEA_DB_NAME}\`.* TO '${GITEA_DB_USER}'@'%';
  GRANT ALL PRIVILEGES ON \`${NEXTCLOUD_DB_NAME}\`.* TO '${NEXTCLOUD_DB_USER}'@'%';
  FLUSH PRIVILEGES;
EOSQL
